image: microsoft/dotnet:latest

stages:
  - build
  - test

variables:
  projectName: "Isis.Architecture.Core.Domain"
  solutionPath: "Solution/Isis.Architecture"
  projectPath: "Projet/Architecture/$projectName"
  testPath: "Test/$projectName.UnitTest"

before_script:
  - "cd $solutionPath" 
  - "dotnet restore"

build:
  stage: build
  variables:
    build_path: "../../$projectPath"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  variables:
    test_path: "../../$testPath"
  script:
    - "cd $test_path"
    - "dotnet test"
